export const ADDED_USER = 'User has been signed up successfully'
export const LOGIN_USER = 'User logs in the app'
export const LOGOUT = 'User logs out of the app'
export const RESET_SETTINGS = 'Reset the values'
export const LOGIN_ERROR = 'Error while login the user'