export const UPDATE_CURRENT = 'Page updates when user selects'
export const UPDATE_TYPE = 'Update the type'
export const UPDATE_INCOME = 'Update the income'
export const UPDATE_PROPERTY = 'Update the property'
export const TOGGLE_PAGE = 'Toggle between the credit page'